### PR TITLE
more necessary python deps

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by biagas** [comment]
@cyrush  our python package needs sure have exploded! Just curious, which package(s) created these requirements?

**Comment by cyrush** [comment]
Turns out they are all needed to build `requests`.

Many are deps of the various hooks needed for the new install commands leveraged by the latest and greatest in zoo of the pip ecosystem. 

During install, they are installed to a sandboxed environment -  so you can only discover them if pip truly cannot reach out to the internet. 

It's pretty wild the true set to modules needed. I guess people have been busy fragmenting away. 

It would be interesting to contrast the handful of packages need to install sphinx, with what it has now grown to. 

I especially love we have to install both `toml` and `tomli`, which are two different modules for reading toml files.

**Comment by biagas** [comment]
I think we build more packages for python now than we do for VisIt!

**Comment by cyrush** [comment]
I know, makes me a bit sad how complex this has grown.

**Pull request merged**
